name: Build Docker Image

on: [push]

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build Docker image
        run: docker build .
